// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVQt8VNkJToqdlptmhm0VN1YfkNZiGlY',
    appId: '1:159652103346:web:c35d4bfd7a7af14d1b35ab',
    messagingSenderId: '159652103346',
    projectId: 'imagineco',
    authDomain: 'imagineco.firebaseapp.com',
    storageBucket: 'imagineco.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4oteBS2Iq1a44n6l52a5uNsQvuyeNISY',
    appId: '1:159652103346:android:692eae1c45cb86d21b35ab',
    messagingSenderId: '159652103346',
    projectId: 'imagineco',
    storageBucket: 'imagineco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAla-l13fqNyL_61hEAmVtSXrtgl3dht3M',
    appId: '1:159652103346:ios:98574fbc4fb551c41b35ab',
    messagingSenderId: '159652103346',
    projectId: 'imagineco',
    storageBucket: 'imagineco.appspot.com',
    iosClientId: '159652103346-asdm1vpq0lk7tjgedpljo3dtie0js154.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagineco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAla-l13fqNyL_61hEAmVtSXrtgl3dht3M',
    appId: '1:159652103346:ios:98574fbc4fb551c41b35ab',
    messagingSenderId: '159652103346',
    projectId: 'imagineco',
    storageBucket: 'imagineco.appspot.com',
    iosClientId: '159652103346-asdm1vpq0lk7tjgedpljo3dtie0js154.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagineco',
  );
}
